#pragma once

enum {COMMAND_ADD, COMMAND_SUB, COMMAND_IF, COMMAND_GOTO, COMMAND_UMINUS, COMMAND_MUL,
	  COMMAND_ASSIGN, COMMAND_DIV, COMMAND_SHIFT, COMMAND_LOR, COMMAND_LAND, COMMAND_RES,
	  COMMAND_VARIABLE,COMMAND_OR,COMMAND_AND,COMMAND_XOR,
	  COMMAND_EQUAL,COMMAND_NEQUAL,COMMAND_LESS,COMMAND_GR,COMMAND_LESSEQU,COMMAND_GREQU,
	  COMMAND_SHL, COMMAND_SHR, COMMAND_INC, COMMAND_DEC, COMMAND_ADDR, COMMAND_REF, 
	  COMMAND_UPLUS, COMMAND_NOT, COMMAND_LNOT, COMMAND_IFNOT, COMMAND_NUMLIT,COMMAND_GLOBAL,COMMAND_RETURN,
	  COMMAND_PARAMETER, COMMAND_ARGUMENT, COMMAND_CALL, COMMAND_CALLVAR, COMMAND_STRLIT};


typedef struct {
	int lineNo;
	int command;
	int op1;
	int op2;
	char not_modify_op1;
	char not_modify_op2;
} interCode;
